# Linear Algebra


Links: https://www.fastcompany.com/90205359/google-you-auto-complete-me

## Dot Products

A dot product is defined as

$ a \cdot b = \sum_{i}^{n} a_{i}b_{i} = a_{1}b_{1} + a_{2}b_{2} + a_{3}b_{3} + \dots + a_{n}b_{n}$

The geometric definition of a dot product is 

$ a \cdot b = $\|\|b\|\|\|\|a\|\|

### What does a dot product conceptually mean?

A dot product is a representation of the similarity between two components, because it is calculated based upon shared elements.


The actual value of a dot product reflects the direction of change:

* **Zero**: we don't have any growth in the original direction
* **Positive** number: we have some growth in the original direction
* **Negative** number: we have negative (reverse) growth in the original direction

In [30]:
A = [0,2]
B = [0,1]

def dot_product(x,y):
    return sum(a*b for a,b in zip(x,y))

dot_product(A,B)
# What will the dot product of A and B be?

-0.4480736161291701

In [ ]:
A = [1,2]
B = [2,4]
# What will the dot product of A and B be?

In [13]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
data_corpus = ["John likes to watch movies. Mary likes movies too.", 
"John also likes to watch football games. Mary does not like football much."]
X = vectorizer.fit_transform(data_corpus) 
print(vectorizer.get_feature_names())

['also', 'does', 'football', 'games', 'john', 'like', 'likes', 'mary', 'movies', 'much', 'not', 'to', 'too', 'watch']


# Bag of Words Models

You can use **`sklearn.feature_extraction.text.CountVectorizer`** to easily convert your corpus into a bag of words matrix:

```python
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
data_corpus = ["John likes to watch movies. Mary likes movies too.", 
"John also likes to watch football games. Mary does not like football much."]
X = vectorizer.fit_transform(data_corpus) 
```
Note that the output `X` here is not your traditional Numpy matrix! Calling **`type(X)`** here will yield **`<class 'scipy.sparse.csr.csr_matrix'>`**, which is a **CSR ([compressed sparse row format matrix](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.sparse.csr_matrix.html))**. To convert it into an actual matrix, call the `toarray()` method:

```python
X.toarray()
```
Your output will be 

```
array([[0, 0, 0, 0, 1, 0, 2, 1, 2, 0, 0, 1, 1, 1],
       [1, 1, 2, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1]], dtype=int64)
```
Notice that using **`X.shape`** $\rightarrow$ `(2,14)`, indicating a total vocabulary size $V$ of 14. To get what word each of the 14 columns corresponds to, use **`vectorizer.get_feature_names()`**:
```
['also', 'does', 'football', 'games', 'john', 'like', 'likes', 'mary', 'movies', 'much', 'not', 'to', 'too', 'watch']
```

Notice, however, that as the vocabulary size $V$ increases, the percent of the matrix taken up by zero values increases:

```python
corpus = [
    "Some analysts think demand could drop this year because a large number of homeowners take on remodeling projectsafter buying a new property. With fewer homes selling, home values easing, and mortgage rates rising, they predict home renovations could fall to their lowest levels in three years.", 
    
          "Most home improvement stocks are expected to report fourth-quarter earnings next month.",
    
         "The conversation boils down to how much leverage management can get out of its wide-ranging efforts to re-energize operations, branding, digital capabilities, and the menu–and, for investors, how much to pay for that.",
    
    "RMD’s software acquisitions, efficiency, and mix overcame pricing and its gross margin improved by 90 bps Y/Y while its operating margin (including amortization) improved by 80 bps Y/Y. Since RMD expects the slower international flow generator growth to continue for the next few quarters, we have lowered our organic growth estimates to the mid-single digits."
]

X = vectorizer.fit_transform(corpus).toarray() 
```



In [60]:
corpus = [
        "Some analysts think demand could drop this year because a large number of homeowners take on remodeling projectsafter buying a new property. With fewer homes selling, home values easing, and mortgage rates rising, they predict home renovations could fall to their lowest levels in three years.", 
    
          "Most home improvement stocks are expected to report fourth-quarter earnings next month.",
    
         "The conversation boils down to how much leverage management can get out of its wide-ranging efforts to re-energize operations, branding, digital capabilities, and the menu–and, for investors, how much to pay for that.",
    
    "RMD’s software acquisitions, efficiency, and mix overcame pricing and its gross margin improved by 90 bps Y/Y while its operating margin (including amortization) improved by 80 bps Y/Y. Since RMD expects the slower international flow generator growth to continue for the next few quarters, we have lowered our organic growth estimates to the mid-single digits. "
]

X = vectorizer.fit_transform(corpus).toarray() 
import numpy as np
from sys import getsizeof

zeroes = np.where(X.flatten() == 0)[0].size 
percent_sparse = zeroes / X.size
print(f"The bag of words feature space is {round(percent_sparse * 100,2)}% sparse. \n\
That's approximately {round(getsizeof(X) * percent_sparse,2)} bytes of wasted memory.")

The bag of words feature space is 72.63% sparse. 
That's approximately 2777.34 bytes of wasted memory.


# Distance Measures


## Euclidean Distance

Euclidean distances can range from 0 (completely identically) to $\infty$ (extremely dissimilar). **Magnitude** plays an extremely important role:

In [8]:
from math import sqrt
 
def euclidean_distance_1(x,y):
    distance = sum((a-b)**2 for a, b in zip(x, y))
    return sqrt(distance)

There's typically an easier way to write this function that takes advantage of Numpy's vectorization capabilities:

In [15]:
import numpy as np
def euclidean_distance_2(x,y):
    x = np.array(x)
    y = np.array(y)
    return np.linalg.norm(x-y)

# Similarity Measures

Similarity measures will always range between -1 and 1. A similarity of -1 means the two objects are complete opposites, while a similarity of 1 indicates the objects are identical.

## Pearson Correlation Coefficient
* We use **ρ** when the correlation is being measured from the population, and **r** when it is being generated from a sample.
* An r value of 1 represents a **perfect linear** relationship, and a value of -1 represents a perfect inverse linear relationship.

The equation for Pearson's correlation coefficient is 
$$
ρ_{Χ_Υ} = \frac{cov(X,Y)}{σ_Xσ_Y}
$$

### Intuition Behind Pearson Correlation Coefficient

#### When $ρ_{Χ_Υ} = 1$ or  $ρ_{Χ_Υ} = -1$

This requires **$cov(X,Y) = σ_Xσ_Y$** or **$-1 * cov(X,Y) = σ_Xσ_Y$** (in the case of $ρ = -1$) . This corresponds with all the data points lying perfectly on the same line.
![Correlations](images/correlation.png "Visualization of various r values for Pearson correlation coefficient")


## Cosine Similarity

The cosine similarity of two vectors (each vector will usually represent one document) is a measure that calculates $ cos(\theta)$, where $\theta$ is the angle between the two vectors.

Therefore, if the vectors are **orthogonal** to each other (90 degrees), $cos(90) = 0$. If the vectors are in exactly the same direction, $\theta = 0$ and $cos(0) = 1$.

Cosine similiarity **does not care about the magnitude of the vector, only the direction** in which it points. This can help normalize when comparing across documents that are different in terms of word count.

### Shift Invariance

* The Pearson correlation coefficient between X and Y does not change with you transform $X \rightarrow a + bX$ and $Y \rightarrow c + dY$, assuming $a$, $b$, $c$, and $d$ are constants and $b$ and $d$ are positive.
* Cosine similarity does, however, change when transformed in this way.


<h1><span style="background-color: #FFFF00">Exercise (20 minutes):</span></h1>

>In Python, find the **cosine similarity** and the **Pearson correlation coefficient** of the two following sentences, assuming a **one-hot encoded binary bag of words** model. You may use a library to create the BoW feature space, but do not use libraries other than `numpy` or `scipy` to compute Pearson, Spearman, and cosine similarity:

>`A = "John likes to watch movies. Mary likes movies too"`

>`B = "John also likes to watch football games, but he likes to watch movies on occasion as well"`

>Your colleagues are having an intense debate about the methodology. The first document another data analyst Tony, says that it doesn't matter if you compare two documents of different lengths. **"Since cosine similarity doesn't care about magnitude, it won't make any real impact,"** he claims. But your manager Bhavna says there is no way this is true and wants you to either normalize the vectors prior to running them through the similarity function or switch to a different similarity metric. What should you do?


#### 1. Create a list of all the **vocabulary $V$**

Using **`sklearn`**'s **`CountVectorizer`**:
```python
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
data_corpus = ["John likes to watch movies. Mary likes movies too", 
"John also likes to watch football games, but he likes to watch movies on occasion as well"]
X = vectorizer.fit_transform(data_corpus) 
V = vectorizer.get_feature_names()
```

##### Native Implementation:
```python
def get_vocabulary(sentences):
    vocabulary = {} # create an empty set - question: Why not a list?
    for sentence in sentences:
         # this is a very crude form of "tokenization", would not actually use in production
        for word in sentence.split(" "):
            if word not in vocabulary:
                vocabulary.add(word)
    return vocabulary
```

#### 2. Create your Bag of Words model
```python
X = X.toarray()
print(X)
```
Your console output:
```python
[[0 0 0 1 2 1 2 1 1 1]
 [1 1 1 1 1 0 0 1 0 1]]
```

#### 3. Define your cosine similarity and Pearson correlation functions

```python
from scipy.spatial.distance import cosine
from numpy import dot
from numpy.linalg import norm

def cosine_similarity(A, B):
    numerator = dot(A, B)
    denominator = norm(A) * norm(B)
    return 1 - numerator / denominator

A = [0,2,3,4,1,2]
B = [1,3,4,0,0,2]

# check that your native implementation and 3rd party library function produce the same values
assert round(cosine_similarity(A,B),4) ==  round(cosine(A,B),4)
```

#### 4. Get the two documents from the BoW feature space and calculate cosine similarity

```python
cosine_similarity(X[0], X[1])
```
>0.5241424183609592

In [99]:
from scipy.spatial.distance import cosine
from numpy import dot
from numpy.linalg import norm

def cosine_similarity(A, B):
    numerator = dot(A, B)
    denominator = norm(A) * norm(B)
    return numerator / denominator # remember, you take 1 - the distance to get the distance

A = [0,2,3,4,1,2]
B = [1,3,4,0,0,2]

# check that your native implementation and 3rd party library function produce the same values
assert round(cosine_similarity(A,B),4) ==  round(1 - cosine(A,B),4)

# check for shift invariance
cosine(np.array(A), B)

0.2494446500534866

In [100]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
data_corpus = ["John likes to watch movies. Mary likes movies too.", 
"John also likes to watch football games."]
X = vectorizer.fit_transform(data_corpus) 
X = X.toarray()
print(vectorizer.get_feature_names())
cosine_similarity(X[0], X[1])

['also', 'football', 'games', 'john', 'likes', 'mary', 'movies', 'to', 'too', 'watch']


0.5241424183609592

# Pointwise Mutual Information

Pointwise mutual information measures the ratio between the **joint probability of two events happening** with the probabilities of the two events happening, assuming they are independent. It can be defined with the following equation:

$$
\begin{equation}
MI_{i,j} = log(\frac{P(i,j)}{P(i)P(j)})
\end{equation}
$$

Remember that when two events are independent, $P(i,j) = P(i)P(j)$.

In [44]:
from nltk.collocations import BigramCollocationFinder, BigramAssocMeasures
from nltk.stem import WordNetLemmatizer
from nltk import word_tokenize
lemmatizer = WordNetLemmatizer()
from nltk.corpus import stopwords
stopwords = set(stopwords.words('english') + [".",",",":", "''", "'s", "'", "``"])

In [45]:
documents = []
articles = [
    "bbcsport/football/001.txt",
    "bbcsport/football/002.txt",
    "bbcsport/football/003.txt"
]

for article in articles:
    article = open(article)
    for line in article.readlines():
        line = line.replace("\n", "")
        if len(line) > 0:

            line = [lemmatizer.lemmatize(token) for token in word_tokenize(line)]
            for word in line:
                if word in stopwords:
                    line.remove(word)
            documents.append(line)

In [46]:
collocation_finder = BigramCollocationFinder.from_documents(documents)
measures = BigramAssocMeasures()

collocation_finder.nbest(measures.raw_freq, 10)

[('Manchester', 'United'),
 ('Van', 'Nistelrooy'),
 ('``', 'I'),
 ('said', '``'),
 ('``', 'He'),
 ('.', "''"),
 ('23', 'minute'),
 ('Alex', 'Ferguson'),
 ('But', 'wa'),
 ('City', 'Sunday')]

# Concepts to Understand

## Statistics
- difference between similarity and distance
- when a dot product versus a cross product is used
- relationship between cosine distance and cosine similarity
- orthogonality
- Manhattan distance
- Mahalanobis distance
- Euclidean distance
- Intersection, Union, Jaccard similarity
- cosine similarity
- pointwise mutual information
- the impact of high-dimensional data on distance measures

## Computer Science
- CSR (compressed sparse row matrix)

## Business / Management